name    'puppet-atheme'
version '0.1.0'
source 'https://github.com/zen/puppet-atheme'
author 'Tomasz "Zen" Napierala'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring Atheme Services (IRC)'
description 'Module for managing and configuring Atheme Services (IRC)'
project_page 'https://github.com/zen/puppet-atheme'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'ripienaar/concat', '>= 0.1.0'
dependency 'hunner/cahrybdis', '>= 0.2.0'